/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebAppsRouteImport } from './routes/web-apps'
import { Route as SocialMediaRouteImport } from './routes/social-media'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as MobileAppsRouteImport } from './routes/mobile-apps'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as DigitalMarketingRouteImport } from './routes/digital-marketing'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WebAppsRoute = WebAppsRouteImport.update({
  id: '/web-apps',
  path: '/web-apps',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialMediaRoute = SocialMediaRouteImport.update({
  id: '/social-media',
  path: '/social-media',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileAppsRoute = MobileAppsRouteImport.update({
  id: '/mobile-apps',
  path: '/mobile-apps',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalMarketingRoute = DigitalMarketingRouteImport.update({
  id: '/digital-marketing',
  path: '/digital-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/digital-marketing': typeof DigitalMarketingRoute
  '/methodology': typeof MethodologyRoute
  '/mobile-apps': typeof MobileAppsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/social-media': typeof SocialMediaRoute
  '/web-apps': typeof WebAppsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/digital-marketing': typeof DigitalMarketingRoute
  '/methodology': typeof MethodologyRoute
  '/mobile-apps': typeof MobileAppsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/social-media': typeof SocialMediaRoute
  '/web-apps': typeof WebAppsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/digital-marketing': typeof DigitalMarketingRoute
  '/methodology': typeof MethodologyRoute
  '/mobile-apps': typeof MobileAppsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/social-media': typeof SocialMediaRoute
  '/web-apps': typeof WebAppsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/digital-marketing'
    | '/methodology'
    | '/mobile-apps'
    | '/privacy-policy'
    | '/social-media'
    | '/web-apps'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/digital-marketing'
    | '/methodology'
    | '/mobile-apps'
    | '/privacy-policy'
    | '/social-media'
    | '/web-apps'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/digital-marketing'
    | '/methodology'
    | '/mobile-apps'
    | '/privacy-policy'
    | '/social-media'
    | '/web-apps'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DigitalMarketingRoute: typeof DigitalMarketingRoute
  MethodologyRoute: typeof MethodologyRoute
  MobileAppsRoute: typeof MobileAppsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SocialMediaRoute: typeof SocialMediaRoute
  WebAppsRoute: typeof WebAppsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/web-apps': {
      id: '/web-apps'
      path: '/web-apps'
      fullPath: '/web-apps'
      preLoaderRoute: typeof WebAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-media': {
      id: '/social-media'
      path: '/social-media'
      fullPath: '/social-media'
      preLoaderRoute: typeof SocialMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-apps': {
      id: '/mobile-apps'
      path: '/mobile-apps'
      fullPath: '/mobile-apps'
      preLoaderRoute: typeof MobileAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-marketing': {
      id: '/digital-marketing'
      path: '/digital-marketing'
      fullPath: '/digital-marketing'
      preLoaderRoute: typeof DigitalMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DigitalMarketingRoute: DigitalMarketingRoute,
  MethodologyRoute: MethodologyRoute,
  MobileAppsRoute: MobileAppsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SocialMediaRoute: SocialMediaRoute,
  WebAppsRoute: WebAppsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
